name = "grip-la-seu-api"
main = "src/index.js"
compatibility_date = "2026-08-13"
account_id = "a758cd1019845ef9a66297e93da0c5b0"

[vars]
SITE_URL = "https://griplaseu.es"
ALLOWED_ORIGIN = "https://griplaseu.es"
OWNER_EMAIL = "grlaseu@gmail.com"
